name: Overall Quality Checks
on: [push, pull_request]

jobs:
  overall_tests_and_code_checks:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8]
        os: [ubuntu-18.04]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8
        if [ -f ci/_requirements.txt ]; then pip install -r ci/_requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --show-source --statistics
    - name: Test with pytest
      run: |
        python -m pip install pytest pytest-cov dash[testing]
        pip install -e .
        pytest --cov-report term-missing --cov --headless -v tests/
